-- this is done in treesitter textobjects plugin
-- mini.ai does not seem to support swap e.g. for moving function arguments around
--
-- local spec_treesitter = require('mini.ai').gen_spec.treesitter
-- require('mini.ai').setup {
--   custom_textobjects = {
--     f = spec_treesitter { a = '@function.outer', i = '@function.inner' },
--     o = spec_treesitter {
--       a = { '@conditional.outer', '@loop.outer' },
--       i = { '@conditional.inner', '@loop.inner' },
--     },
--   },
-- }
